### ISSUE TITLE
SQL Data types

### ISSUE THREAD

**Issue by rtrevelar** [jingwu1986/DatabaseMigration#1]
in GetTableColumns, adding "left join sys.types sty on c.user_type_id = sty.user_type_id" then include return field "sty.is_user_defined"

when sty.is_user_defined=1, it gives an error as DataType value is no longer correct.

I tried based on AdventureWorks2014 SQLServer database

**Comment by jingwu1986** [comment]
A new property “IsUserDefined“ has been added to TableColumn class. In addition, user defined type of SqlServer can be generated now.
